main: Loremaster
api-version: '1.16'

name: Loremaster
version: '0.2.0'
description: da
author: Veikmaster

commands:

  Loremaster:
    aliases: lore
    description: Loremaster command
    usage: "§bHold the item into which you wish to write lore, and type§r /<command> §nwrite lore here§r.
    §bYou can use color codes in the lore: §9§nhttps://www.spigotmc.org/attachments/example2-png.188806/§r
    §bUse a separate \\n to add manual line breaks.
    By default, an item can have lore written to it only once, so be careful not to mess up!"
    tab-complete: -1
    permission: lore.core

  Loreclear:
    description: Command to clear lore
    usage: "Hold the item from which you wish to clear lore"
    permission: lore.op

permissions:
  lore.core:
    default: true

  lore.op:
    default: op